name: Build and Push Docker Tag

on:
  push:
    tags:
      # Poprawiony wzorzec: uruchamia dla tagów zaczynających się od 'v', np. v1.0.3
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Zaktualizowano z v2 do v4 (najnowsza stabilna wersja)
      uses: actions/checkout@v4 

    - name: Login to Docker Hub
      # Ta akcja jest aktualna
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      # Ta akcja jest aktualna
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # Uzywa nazwy taga git jako taga obrazu dockera (np. m260678m-afk/kalkulator:v1.0.3)
        tags: m260678m-afk/kalkulator:${{ github.ref_name }}
